In [1]:
import torch
import numpy as np
import warnings
warnings.filterwarnings(action='ignore')

C:\Users\korea\anaconda3\envs\py39\lib\site-packages\tqdm\auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


#### Pytorch 기본 연산 단위 : Tensor

In [2]:
print(f'pytorch tensor : {torch.tensor([1,2,3,4,5]).dtype}')
print(f'pytorch tensor : {torch.tensor([1.0,2.0,3.0,4.0,5.0]).dtype}')

pytorch tensor : torch.int64
pytorch tensor : torch.float32


In [3]:
a = [1,2,3,4,5]

a_long = torch.LongTensor(a)
a_float = torch.FloatTensor(a)

print(f'pytorch 기본 정수 데이터 타입 {a_long.dtype} | 텐서 타입 {a_long.type()}')
print(f'pytorch 기본 실수 데이터 타입 {a_float.dtype} | 텐서 타입 {a_float.type()}')

pytorch 기본 정수 데이터 타입 torch.int64 | 텐서 타입 torch.LongTensor
pytorch 기본 실수 데이터 타입 torch.float32 | 텐서 타입 torch.FloatTensor


#### Data type 변경방법

In [4]:
a = torch.LongTensor([1,2,3,4,5])
print(f'변경 전 data type : {a.dtype}')
print(f'변경 후 data type : {a.type(torch.FloatTensor).dtype}')
print(f'변경 후 data type : {a.float().dtype}')

변경 전 data type : torch.int64
변경 후 data type : torch.float32
변경 후 data type : torch.float32


#### numpy to tensor / tensor to numpy

In [5]:
# numpy to tensor
a = np.array([1,2,3,4,5])
print(torch.from_numpy(a).type())
print(torch.tensor(a).type())
print(torch.LongTensor(a).type())

torch.IntTensor
torch.IntTensor
torch.LongTensor


In [6]:
# tensor to numpy
a = torch.LongTensor([1,2,3,4,5])
print(type(a.numpy()))

<class 'numpy.ndarray'>


#### CPU & GPU

In [7]:
# GPU를 사용할 수 있는지 없는지 확인
torch.cuda.is_available()

True

In [8]:
# tensor의 위치 확인
a = torch.FloatTensor([1,2,3,4,5])
a.device

device(type='cpu')

In [9]:
# CPU to GPU
print(a.cuda().device)
print(a.to('cuda:0').device)
print(a.to(0).device)

cuda:0
cuda:0
cuda:0


In [10]:
# GPU to CPU
a = torch.FloatTensor([1,2,3,4,5]).to(0)
print(f'{a.device} to {a.cpu().device}')
print(f'{a.device} to {a.to("cpu").device}')

cuda:0 to cpu
cuda:0 to cpu


In [11]:
# 텐서의 위치가 다르면 에러 발생
a = torch.FloatTensor([1,2,3,4,5]).to(0)
a + a.cpu()

RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

#### Tensor 조작하기
##### 1. index를 활용한 데이터 선택

In [12]:
a = torch.FloatTensor([[1,2,3],
                       [4,5,6],
                       [7,8,9]])
a

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [13]:
# index를 활용한 i번째 row 선택
i=2
print(a[i])
print(a[i,:])

tensor([7., 8., 9.])
tensor([7., 8., 9.])


In [14]:
# index를 활용한 j번째 column 선택
j=1
print(a[:,j])

tensor([2., 5., 8.])


In [15]:
# index를 활용한 i번째 row,j번째 column element 선택
i,j = 2,1
print(a[i,j])

tensor(8.)


In [16]:
# index를 활용한 i~j-1까지 row or column 선택
i,j = 1,3
print(a[i:j,:])
print(a[:,i:j])

tensor([[4., 5., 6.],
        [7., 8., 9.]])
tensor([[2., 3.],
        [5., 6.],
        [8., 9.]])


In [17]:
print(a[1:3,1:3])

tensor([[5., 6.],
        [8., 9.]])


##### 2. 특정 조건을 만족하는 데이터 선택

In [18]:
# 특정 조건을 만족하는 element 선택 -> 특정 조건을 만족하는지 만족하지 않는지 True False mask를 만들어야 함
# ex1) 클래스가 5인 x만을 선택
x = torch.randn(size=(32,5)) # 특징(X)이 5개 있는 입력 변수 32개 생성
labels = torch.randint(0,6,size=(32,)) # 0~5의 class를 가지는 출력 변수 32개 생성
print(labels)
print((labels==5).sum())


tensor([5, 3, 4, 3, 4, 5, 1, 4, 4, 3, 3, 3, 1, 1, 0, 1, 3, 1, 1, 2, 1, 2, 2, 1,
        4, 2, 4, 4, 0, 0, 1, 2])
tensor(2)


In [19]:
mask = labels == 5
print(mask)

print(x[mask])
print(x[mask].shape)

tensor([ True, False, False, False, False,  True, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False])
tensor([[ 0.7928,  2.0665,  0.7490,  0.2729, -0.0196],
        [-0.1831, -0.9246, -0.8593, -0.5203,  0.5959]])
torch.Size([2, 5])


In [20]:
# mask를 만드는 방법
print(labels==5)
print(torch.where(labels==5,True,False))
print(labels.eq(5))

# 참고 : element-wise compairsion function / 두 텐서간 비교도 가능

# torch.ne = not_equal
# torch.eq = equal
# torch.ge = greater_equal
# torch.le = less_equal
# torch.greater
# torch.less

tensor([ True, False, False, False, False,  True, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False])
tensor([ True, False, False, False, False,  True, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False])
tensor([ True, False, False, False, False,  True, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False])


In [21]:
# 다중조건 mask를 만드는 방법
print((labels>=3) & (labels<=5))
print(torch.mul(labels>=3,labels<=5))

tensor([ True,  True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True, False, False, False, False,  True, False, False, False,
        False, False, False, False,  True, False,  True,  True, False, False,
        False, False])
tensor([ True,  True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True, False, False, False, False,  True, False, False, False,
        False, False, False, False,  True, False,  True,  True, False, False,
        False, False])


##### 3.특정 조건을 만족하는 데이터의 인덱스 얻기

In [22]:
x = torch.randn(size=(32,5))
labels = torch.randint(0,6,size=(32,))
print(labels)
print((labels==5).sum())

mask = labels==5
print(mask)

tensor([5, 4, 0, 5, 1, 1, 1, 2, 1, 0, 1, 3, 3, 5, 3, 0, 1, 5, 2, 1, 1, 5, 2, 1,
        2, 3, 4, 5, 0, 2, 4, 1])
tensor(6)
tensor([ True, False, False,  True, False, False, False, False, False, False,
        False, False, False,  True, False, False, False,  True, False, False,
        False,  True, False, False, False, False, False,  True, False, False,
        False, False])


In [23]:
print(torch.nonzero(mask))

tensor([[ 0],
        [ 3],
        [13],
        [17],
        [21],
        [27]])


#### 텐서 연산

##### 1. 통계량 계산

In [24]:
a = torch.FloatTensor([[1,2,3],
                       [4,5,6],
                       [7,8,9]])
a

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [25]:
# sum, mean, max, min, std
print(torch.sum(a)) # a.sum()
print(torch.mean(a)) # a.mean()
print(torch.std(a)) # a.std()
print(torch.max(a)) # a.max()
print(torch.min(a)) # a.min()

tensor(45.)
tensor(5.)
tensor(2.7386)
tensor(9.)
tensor(1.)


In [26]:
# 특정 dimension을 기준으로 계산
print(torch.sum(a, dim=0))
print(torch.mean(a, dim=0))
print(torch.std(a, dim=0))
print(torch.max(a, dim=0)) # 최대값과 최대값 인덱스를 같이 반환
print(torch.min(a, dim=0)) # 최소값과 최소값 인덱스를 같이 반환

tensor([12., 15., 18.])
tensor([4., 5., 6.])
tensor([3., 3., 3.])
torch.return_types.max(
values=tensor([7., 8., 9.]),
indices=tensor([2, 2, 2]))
torch.return_types.min(
values=tensor([1., 2., 3.]),
indices=tensor([0, 0, 0]))


##### 2. element-wise 연산

In [27]:
a = torch.FloatTensor([1,2,3,4,5,6])
b = torch.FloatTensor([4,5,6,7,8,9])

In [28]:
print(f'상수항 더하기 : {a + 1}')
print(f'상수항 곱하기 : {a * 2}')

상수항 더하기 : tensor([2., 3., 4., 5., 6., 7.])
상수항 곱하기 : tensor([ 2.,  4.,  6.,  8., 10., 12.])


In [29]:
print(f'두 텐서 간 element-wise 더하기 : {a + b}')
print(f'두 텐서 간 element-wise 곱하기 : {a * b}')

두 텐서 간 element-wise 더하기 : tensor([ 5.,  7.,  9., 11., 13., 15.])
두 텐서 간 element-wise 곱하기 : tensor([ 4., 10., 18., 28., 40., 54.])


In [30]:
print(f'함수를 활용한 element-wise 더하기 : {torch.add(a,1)}')
print(f'함수를 활용한 element-wise 더하기 : {torch.add(a,b)}')
print(f'함수를 활용한 element-wise 곱하기 : {torch.mul(a,2)}')
print(f'함수를 활용한 element-wise 곱하기 : {torch.mul(a,b)}')
# 나누기 = torch.div
# 제곱 = torch.pow
# 지수 = torch.exp
# 로그 = torch.log


함수를 활용한 element-wise 더하기 : tensor([2., 3., 4., 5., 6., 7.])
함수를 활용한 element-wise 더하기 : tensor([ 5.,  7.,  9., 11., 13., 15.])
함수를 활용한 element-wise 곱하기 : tensor([ 2.,  4.,  6.,  8., 10., 12.])
함수를 활용한 element-wise 곱하기 : tensor([ 4., 10., 18., 28., 40., 54.])


In [31]:
# 특정 dimension만 더하고 싶으면 해당 dimension의 data를 선택한 후 변경
a = torch.FloatTensor([[1,2,3],
                       [4,5,6],
                       [7,8,9]])

b = torch.FloatTensor([[11,12,13],
                       [14,15,16],
                       [17,18,19]])

a[:,0] = a[:,0] + b[:,0]

print(a)

tensor([[12.,  2.,  3.],
        [18.,  5.,  6.],
        [24.,  8.,  9.]])


##### 3. 벡터/행렬 연산

In [32]:
# 두 벡터 간 내적 외적
a = torch.tensor([1,2,3,4])
b = torch.tensor([2,3,4,5])
c = torch.dot(a,b)
print(c) # tensor(40)

d = torch.outer(a,b)
print(d)

tensor(40)
tensor([[ 2,  3,  4,  5],
        [ 4,  6,  8, 10],
        [ 6,  9, 12, 15],
        [ 8, 12, 16, 20]])


In [33]:
# 벡터, 행렬 전치
a = torch.FloatTensor([[1,2,3],
                       [4,5,6],
                       [7,8,9]])
print(a.t()) # a.T

tensor([[1., 4., 7.],
        [2., 5., 8.],
        [3., 6., 9.]])


In [34]:
# 행렬곱
a = torch.randint(1,10, size=(5,4))
b = torch.randint(1,10, size=(6,4))
print(a)
print(b)


tensor([[5, 7, 8, 4],
        [9, 9, 8, 9],
        [9, 7, 8, 4],
        [5, 3, 2, 9],
        [1, 3, 8, 1]])
tensor([[6, 6, 1, 3],
        [2, 9, 7, 5],
        [3, 6, 9, 9],
        [5, 6, 4, 1],
        [5, 5, 3, 6],
        [7, 1, 4, 6]])


In [35]:
#matmul은 행렬-벡터 간 연산 가능, mm은 행렬-행렬만 지원
c = torch.matmul(a,b.t()) # torch.mm(a,b.T)

print(c)
print(c.shape) # c.size()

tensor([[ 92, 149, 165, 103, 108,  98],
        [143, 200, 234, 140, 168, 158],
        [116, 157, 177, 123, 128, 126],
        [ 77,  96, 132,  60, 100, 100],
        [ 35,  90, 102,  56,  50,  48]])
torch.Size([5, 6])


##### 4. 텐서 결합/분해하기

In [36]:
a = torch.FloatTensor([[1,2,3],
                       [4,5,6],
                       [7,8,9]])

b = torch.FloatTensor([[11,12,13],
                       [14,15,16],
                       [17,18,19]])

row_cat = torch.cat((a,b),dim=0)
col_cat = torch.cat((a,b),dim=1)

print(row_cat, row_cat.shape)
print(col_cat, col_cat.shape)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [11., 12., 13.],
        [14., 15., 16.],
        [17., 18., 19.]]) torch.Size([6, 3])
tensor([[ 1.,  2.,  3., 11., 12., 13.],
        [ 4.,  5.,  6., 14., 15., 16.],
        [ 7.,  8.,  9., 17., 18., 19.]]) torch.Size([3, 6])


In [37]:
stack_dim0 = torch.stack((a,b),dim=0)
print(stack_dim0, stack_dim0.shape)

tensor([[[ 1.,  2.,  3.],
         [ 4.,  5.,  6.],
         [ 7.,  8.,  9.]],

        [[11., 12., 13.],
         [14., 15., 16.],
         [17., 18., 19.]]]) torch.Size([2, 3, 3])


In [38]:
stack_dim1 = torch.stack((a,b),dim=1)
print(stack_dim1, stack_dim1.shape)

tensor([[[ 1.,  2.,  3.],
         [11., 12., 13.]],

        [[ 4.,  5.,  6.],
         [14., 15., 16.]],

        [[ 7.,  8.,  9.],
         [17., 18., 19.]]]) torch.Size([3, 2, 3])


In [39]:
# 하나의 텐서를 n개의 텐서로 분해하기
a = torch.FloatTensor([
    [ 1.,  2.,  3.],
    [ 4.,  5.,  6.],
    [-1., -2., -3.],
    [-4., -5., -6.]
])
print(torch.chunk(a,chunks=4,dim=0))

(tensor([[1., 2., 3.]]), tensor([[4., 5., 6.]]), tensor([[-1., -2., -3.]]), tensor([[-4., -5., -6.]]))


In [40]:
# 하나의 텐서를 n개의 row를 가지는 텐서로 분리하기
print(torch.split(a,split_size_or_sections=1,dim=0))

(tensor([[1., 2., 3.]]), tensor([[4., 5., 6.]]), tensor([[-1., -2., -3.]]), tensor([[-4., -5., -6.]]))


#### 5. 차원 늘리기/줄이기/바꾸기

In [41]:
# 차원 늘리기
a = torch.randn(size=(10,3))
b = torch.randn(size=(3,))
print(a.shape, b.shape)

torch.Size([10, 3]) torch.Size([3])


In [42]:
# 차원의 개수가 다르면 에러 발생
print(torch.cat((a,b),dim=0))

RuntimeError: Tensors must have same number of dimensions: got 2 and 1

In [43]:
print(torch.cat((a,b.unsqueeze(dim=0)),dim=0).shape)

torch.Size([11, 3])


In [44]:
# 차원 줄이기
a = torch.randn(size=(1,10,3))
b = torch.randn(size=(5,3))

print(torch.cat((a.squeeze(dim=0),b),dim=0).shape)

torch.Size([15, 3])


In [45]:
# 차원 변경
image = torch.randn(size=(32,32,3))
print(f'{image.shape} -> {image.transpose(0,2).shape}')

torch.Size([32, 32, 3]) -> torch.Size([3, 32, 32])


In [46]:
# 차원을 여러 개로 변경
images = torch.randn(size=(32,32,3,128))
print(f'{images.shape} -> {images.permute(3,2,0,1).shape}')

torch.Size([32, 32, 3, 128]) -> torch.Size([128, 3, 32, 32])


In [47]:
# 차원 재배열
image = torch.randn(size=(3,32,32))

print(image.reshape(3,32*32).shape)
print(image.view(3,32*32).shape)

torch.Size([3, 1024])
torch.Size([3, 1024])


#### pytorch 자동미분

In [48]:
def f(x):
    y = x**3 + 2*x**2+7
    return y

def g(x):
    y = x**2
    return y

In [49]:
x = torch.tensor(3.0, requires_grad=True)

f_x = f(x)
f_x.backward()
print(f'f_x를 x로 미분한 값 : {x.grad}')

f_x를 x로 미분한 값 : 39.0


In [50]:
x = torch.tensor(3.0, requires_grad=True)

g_x = g(x)
g_x.backward()
print(f'g_x를 x로 미분한 값 : {x.grad}')

f_x를 x로 미분한 값 : 6.0


In [51]:
x = torch.tensor(3.0, requires_grad=True)

g_f_x = g(f(x))
g_f_x.backward()
print(f"g(f(x))를 x로 미분한 값 = f'(3)*g'(f(3)) = 39*2*52 = {x.grad}")

g(f(x))를 x로 미분한 값 = f'(3)*g'(f(3)) = 39*2*52 = 4056.0


In [52]:
x = torch.randn(size=(10,)) # 입력 변수가 10개인 관측치 한 개
y = torch.tensor(1.0) # x에 해당하는 출력 변수

w1 = torch.randn(size=(10,5),requires_grad=True) # linear layer1
w2 = torch.randn(size=(5,1),requires_grad=True) # linear layer2

In [53]:
y_pred = torch.matmul((torch.matmul(x,w1)),w2) # forward

loss = (y-y_pred)**2 # MSE Loss 계산

print(loss)

loss.backward() #backward

print(w1.grad)
print(w2.grad)

tensor([168.9308], grad_fn=<PowBackward0>)
tensor([[  1.5966,  -2.5086,   1.7700,   9.1995,   3.1415],
        [ -1.4277,   2.2432,  -1.5828,  -8.2264,  -2.8092],
        [-11.9845,  18.8300, -13.2859, -69.0532, -23.5808],
        [ 17.3093, -27.1964,  19.1890,  99.7346,  34.0580],
        [-16.8010,  26.3977, -18.6255, -96.8055, -33.0578],
        [  4.6662,  -7.3314,   5.1729,  26.8859,   9.1812],
        [ 11.9748, -18.8147,  13.2752,  68.9973,  23.5617],
        [ -6.7186,  10.5562,  -7.4482, -38.7116, -13.2195],
        [ 13.9038, -21.8456,  15.4137,  80.1123,  27.3573],
        [  3.8971,  -6.1231,   4.3203,  22.4544,   7.6679]])
tensor([[ 17.8550],
        [ -8.5876],
        [163.5132],
        [117.5072],
        [ 51.7092]])


#### zero_grad

In [54]:
# backward를 통해 계산된 gradient는 backward를 할 때마다 누적
# 따라서 backward를 한 번 한 뒤, 초기화가 필요

x = torch.FloatTensor([1,2,3])
x.requires_grad = True
print(x, '\n')
out = (x+1).pow(2).t() # 미분함수 f'(x) = 2(x+1)
out.backward(torch.ones_like(out), retain_graph=True)

print(f"First call\n{x.grad}")
out.backward(torch.ones_like(out), retain_graph=True)

print(f"\nSecond call\n{x.grad}")
x.grad.zero_()
out.backward(torch.ones_like(out), retain_graph=True)
print(f"\nCall after zeroing gradients\n{x.grad}")

tensor([1., 2., 3.], requires_grad=True) 

First call
tensor([4., 6., 8.])

Second call
tensor([ 8., 12., 16.])

Call after zeroing gradients
tensor([4., 6., 8.])


#### stop backward

In [55]:
# backward 단계에서 detach 이전 layer에는 gradient 계산을 멈춤

x = torch.randn(size=(10,)) # 입력변수가 10개인 관측치
y = torch.tensor(1.0)

w1 = torch.randn(size=(10,5),requires_grad=True)
w2 = torch.randn(size=(5,1),requires_grad=True)

In [56]:
y_pred = torch.matmul((torch.matmul(x,w1)).detach(),w2)

loss = (y-y_pred)**2

print(loss)

loss.backward()

print(w1.grad)
print(w2.grad)

tensor([52.5626], grad_fn=<PowBackward0>)
None
tensor([[ 32.0475],
        [-88.1717],
        [ 28.8982],
        [-43.5469],
        [  0.5812]])


#### stop autograd

In [57]:
# backward를 위한 computation graph를 만드는 것은 연산 시간을 늘림
# backward가 필요없는 구간에서는 자동 미분을 끄는 용도 (모델 테스트 단계)

x = torch.randn(size=(10,)) # 입력변수가 10개인 관측치
y = torch.tensor(1.0)

w1 = torch.randn(size=(10,5),requires_grad=True)
w2 = torch.randn(size=(5,1),requires_grad=True)

In [58]:
with torch.no_grad():
    y_pred = torch.matmul((torch.matmul(x,w1)).detach(),w2)

    loss = (y-y_pred)**2

print(y_pred)
print(loss)

tensor([-2.1091])
tensor([9.6664])
